image: gitpod/workspace-mysql # Configurando a imagem (ambiente) do gitpod para inciar com o mysql.

tasks:  # Abrindo a lista de tarefas.
  - init: mysql -u root -e "CREATE DATABASE applicationdb"  # Tarefa ao iniciar o ambiente que acessa o usuário root do mysql e cria a base de dados "applicationdb".